[package]
name = "raytracer_codegen"
version = "0.1.0"
authors = ["Pseudo Photograph Company of ACM <ppca@ppca.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = "1.0"
proc-macro2 = "1.0"
rand = "0.8.3"
serde_json = "1.0"
criterion = "0.3"


